### ISSUE TITLE
testFail doesn't pass on throw

### ISSUE THREAD

**Issue by warren-bank** [dapphub/dapp#24]
Hi all. I'm really sorry if this is pilot error. I'm brand new to using `dapp`. I just installed it and planned to test a few sample contracts.

I'm on:
* Lubuntu 16.04.2 LTS (64-bit)
* node v7.9.0
* dapp (commit a75a4bd)
* ethrun v0.2.1

Basically, everything is brand new.. and there were no problems installing `dapp` or any of its dependencies.

`dapp init` includes a test contract, and performs a sanity check:

```javascript
pragma solidity ^0.4.8;

import "ds-test/test.sol";

contract Test is DSTest {
    function test_basic_sanity() {
        assert(true);
    }

    function testFail_basic_sanity() {
        assert(false);
    }
}
```

..but I'm seeing **testFail_basic_sanity** fail:

```bash
$ cd ~/my_dapp
$ dapp init

+ git init
Initialized empty Git repository in ~/my_dapp/.git/
+ mkdir -p lib src
+ git add .gitignore
+ git add Makefile
+ git add Dappfile
+ git add src/test.sol
+ git commit -m 'dapp-init my_dapp'
[master (root-commit) 60d0b52] dapp-init my_dapp
 4 files changed, 22 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 Dappfile
 create mode 100644 Makefile
 create mode 100644 src/test.sol
+ dapp install ds-test
+ git submodule add --force https://github.com/dapphub/ds-test lib/ds-test
Cloning into 'lib/ds-test'...
+ git submodule update --init --recursive
+ git commit -m 'dapp-install dapphub/ds-test'
[master 4e28a0e] dapp-install dapphub/ds-test
 2 files changed, 4 insertions(+)
 create mode 100644 .gitmodules
 create mode 160000 lib/ds-test
+ make test
dapp test
+ dapp clean
+ rm -rf out
+ solc --overwrite --abi --bin --bin-runtime = -o out ds-test=lib/ds-test/src src/test.sol
Trying Test...
.F

  [NOFAIL] testFail_basic_sanity
    (no details)

1 tests passed, 1 failed
Took 0.507s
Makefile:2: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by warren-bank** [comment]
What's more..

I'm also seeing tests pass, which **should** fail.

My 2nd test contract was borrowed from the [blog post](https://blog.dapphub.com/saving-time-and-sanity-using-the-next-generation-of-dapple-testing-tools/) that describes the advantages of `dapple-quicktest`. Since that code made its way into this project, I just wanted to confirm the same output.

```javascript
pragma solidity ^0.4.10;

import "ds-test/test.sol";

contract FooTest is DSTest {
    function setUp() {}

    function foo() {
        throw;
    }

    function test_foo() {
        this.foo();
    }
}
```

and yet.. despite the fact that it clearly throws an exception, this is the output of the test runner:

```bash
$ dapp test

+ dapp clean
+ rm -rf out
+ solc --overwrite --abi --bin --bin-runtime = -o out ds-test=lib/ds-test/src src/FooTest.sol
Trying FooTest...
.

1 tests passed, 0 failed
Took 0.286s
```

I must be doing something wrong, but I don't have a clue what that could be. Could somebody (much smarter than me) please share some wisdom? Thanks. :)

**Comment by dbrock** [comment]
@warren-bank I'm sorry, this is because of a fuckup I made when adding a feature to `ethrun` recently. Basically ethrun-0.2.0 and ethrun-0.2.1 are totally broken.

The error was fixed in ethrun-0.2.2, so see if you can upgrade to that.

(Also, thanks for the nice bug report.)

**Comment by warren-bank** [comment]
No apology needed.. I'm just really glad that you were able to track the problem down so quickly. (Rockstar!)

I'll update `ethrun` and give it a whirl. Thanks again! :)

**Comment by warren-bank** [comment]
wow.. just wow!
..I'm loving this test harness.

given the sample contract:
```javascript
pragma solidity ^0.4.8;

import "ds-test/test.sol";

// ------------------------------

contract C_01 {
  C_02 next;

  function C_01 () {
    next = new C_02();
  }

  function exec () {
    next.exec();
  }
}

// ------------------------------

contract C_02 {
  C_03 next;

  function C_02 () {
    next = new C_03();
  }

  function exec () {
    next.exec();
  }
}

// ------------------------------

contract C_03 {
  C_04 next;

  function C_03 () {
    next = new C_04();
  }

  function exec () {
    next.exec();
  }
}

// ------------------------------

contract C_04 {
  function exec () {
    throw;
  }
}

// ------------------------------

contract Test is DSTest {
    function test_nested_contract_transactions() {
        C_01 domino = new C_01();
        domino.exec();
    }
}
```
and for fun.. lets just compare the test results using both `truffle test` vs. `dapp test`

**truffle:**
```bash
Compiling ./contracts/C_01.sol...
Compiling ./test/Test.sol...
Compiling truffle/Assert.sol...


  Test
    1) test_nested_contract_transactions
    > No events were emitted


  0 passing (820ms)
  1 failing

  1) Test test_nested_contract_transactions:
     Error: VM Exception while processing transaction: out of gas
      at Object.InvalidResponse (/home/warren/lib/node_modules/truffle/node_modules/web3/lib/web3/errors.js:35:16)
      at /home/warren/lib/node_modules/truffle/node_modules/web3/lib/web3/requestmanager.js:86:36
      at XMLHttpRequest.request.onreadystatechange (/home/warren/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:118:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/home/warren/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:64:18)
      at XMLHttpRequest._setReadyState (/home/warren/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:354:12)
      at XMLHttpRequest._onHttpResponseEnd (/home/warren/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:509:12)
      at IncomingMessage.<anonymous> (/home/warren/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:469:24)
      at endReadableNT (_stream_readable.js:975:12)
```

and now,<br>
**dapp:**
```bash
Trying Test...
F

  [CRASH] test_nested_contract_transactions
         Dapple -> <Test#d289>.test_nested_contract_transactions() => BadInstruction
    <Test#d289> ->   new C_01(...) => <C_01#f0b2>
    <C_01#f0b2> ->     new C_02(...) => <C_02#6261>
    <C_02#6261> ->       new C_03(...) => <C_03#297a>
    <C_03#297a> ->         new C_04(...) => <C_04#3a63>
    <Test#d289> ->   <C_01#f0b2>.exec() => BadInstruction
    <C_01#f0b2> ->     <C_02#6261>.exec() => BadInstruction
    <C_02#6261> ->       <C_03#297a>.exec() => BadInstruction
    <C_03#297a> ->         <C_04#3a63>.exec() => BadInstruction

0 tests passed, 1 failed
Took 0.625s
```

**Comment by warren-bank** [comment]
oops..

looks like the workhorse script still [uses `dapple`](https://github.com/dapphub/dapp/blob/a215f7b4bdab00d0414030d0284d951fb2226031/libexec/dapp/dapp-quicktest#L58),<br>and still [refers to itself by the 'Dapple' moniker](https://github.com/dapphub/dapp/blob/a215f7b4bdab00d0414030d0284d951fb2226031/libexec/dapp/dapp-quicktest#L199)

**Comment by apmilen** [comment]
@dbrock can we remove all reliance on and references to dapple plz?
