### ISSUE TITLE
Unable to run tests when unused library in subdirectory

### ISSUE THREAD

**Issue by travs** [dapphub/dapp#59]
If I have a library in a subdirectory of `src` (e.g. `src/exchange/adapters/fakeLib.sol`) that I do not import anywhere else, then when running `dapp test` it fails.

Output:

```
+ dapp quicktest out out/FakeLib.bin out/simpleAdapter.bin out/rewards.bin out/safeMath.bin
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
fs.js:652
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'out/FakeLib.bin'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at readBytes (/home/travis/prg/dapp/libexec/dapp/dapp-quicktest:103:29)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/travis/prg/dapp/libexec/dapp/dapp-quicktest:104:39)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

For now the easiest thing for me to do is just move the unused library to another directory, but we will want it back at some point.

I'm guessing this happens because the build step doesn't put the library in the root `out/` directory?

**Comment by mbrock** [comment]
This should be fixed with dapp v0.6.4 which is now in the Nix channel.
